<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/14 0014
 * Time: 14:41
 */

namespace app\www\controller;


use think\Controller;
use think\Log;
use app\admin\model\NewsModel;

class NewsController extends Controller
{
    private  $news;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->news = new NewsModel();
    }

    public function news(){
        try{
            $list = $this->news->paginate(6);
            $img=config("news_upload_path");
            $this->assign('img_path',$img);
            $this->assign('list',$list);
        }catch (\Exception $e){
            Log::write($e->getMessage(),'error');
        }
        return $this->fetch('news');
    }

    public function newsInfo(){
        try{

        }catch (\Exception $e){
            Log::write($e->getMessage(),'error');
        }
        return $this->fetch('news_info');
    }
}